### ISSUE TITLE
Undefined method LoggerProxy::warn 

### ISSUE THREAD

**Issue by evs-xsarus** [flowmailer/m2connector#12]
Using Magento 2.4.2-p1 with flowmailer/m2connector 1.0.13 , I get this error. Could this be fixed?

==> var/log/debug.log <==
```log
[2021-05-26 13:14:23] main.CRITICAL: Error: Call to undefined method Magento\Framework\Logger\LoggerProxy::warn() in /sites/tex-upgrade/current/vendor/flowmailer/m2connector/Plugin/TransportPlugin.php:197
Stack trace:
#0 /sites/tex-upgrade/current/vendor/magento/framework/Interception/Interceptor.php(135): Flowmailer\M2Connector\Plugin\TransportPlugin->aroundSendMessage(Object(Magento\Email\Model\Transport\Interceptor), Object(Closure))
#1 /sites/tex-upgrade/current/vendor/magento/module-email/Model/Mail/TransportInterfacePlugin.php(48): Magento\Email\Model\Transport\Interceptor->Magento\Framework\Interception\{closure}()
#2 /sites/tex-upgrade/current/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Email\Model\Mail\TransportInterfacePlugin->aroundSendMessage(Object(Magento\Email\Model\Transport\Interceptor), Object(Closure))
#3 /sites/tex-upgrade/current/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Email\Model\Transport\Interceptor->Magento\Framework\Interception\{closure}()
#4 /sites/tex-upgrade/current/generated/code/Magento/Email/Model/Transport/Interceptor.php(23): Magento\Email\Model\Transport\Interceptor->___callPlugins('sendMessage', Array, NULL)
#5 /sites/tex-upgrade/current/vendor/magento/module-two-factor-auth/Model/EmailUserNotifier.php(106): Magento\Email\Model\Transport\Interceptor->sendMessage()
#6 /sites/tex-upgrade/current/vendor/magento/module-two-factor-auth/Model/EmailUserNotifier.php(135): Magento\TwoFactorAuth\Model\EmailUserNotifier->sendConfigRequired(Object(Magento\User\Model\User\Interceptor), 'eyJ1c2VyX2lkIjo...', 'tfa_admin_app_c...', 'https://evs74mg...')
#7 /sites/tex-upgrade/current/vendor/magento/module-two-factor-auth/Model/UserConfig/UserConfigRequestManager.php(82): Magento\TwoFactorAuth\Model\EmailUserNotifier->sendAppConfigRequestMessage(Object(Magento\User\Model\User\Interceptor), 'eyJ1c2VyX2lkIjo...')
#8 /sites/tex-upgrade/current/vendor/magento/module-two-factor-auth/Controller/Adminhtml/Tfa/Requestconfig.php(92): Magento\TwoFactorAuth\Model\UserConfig\UserConfigRequestManager->sendConfigRequestTo(Object(Magento\User\Model\User\Interceptor))
#9 /sites/tex-upgrade/current/vendor/magento/framework/Interception/Interceptor.php(58): Magento\TwoFactorAuth\Controller\Adminhtml\Tfa\Requestconfig->execute()
#10 /sites/tex-upgrade/current/vendor/magento/framework/Interception/Interceptor.php(138): Magento\TwoFactorAuth\Controller\Adminhtml\Tfa\Requestconfig\Interceptor->___callParent('execute', Array)
#11 /sites/tex-upgrade/current/vendor/magento/framework/App/Action/Plugin/ActionFlagNoDispatchPlugin.php(51): Magento\TwoFactorAuth\Controller\Adminhtml\Tfa\Requestconfig\Interceptor->Magento\Framework\Interception\{closure}()
#12 /sites/tex-upgrade/current/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Framework\App\Action\Plugin\ActionFlagNoDispatchPlugin->aroundExecute(Object(Magento\TwoFactorAuth\Controller\Adminhtml\Tfa\Requestconfig\Interceptor), Object(Closure))
#13 /sites/tex-upgrade/current/vendor/magento/framework/Interception/Interceptor.php(153): Magento\TwoFactorAuth\Controller\Adminhtml\Tfa\Requestconfig\Interceptor->Magento\Framework\Interception\{closure}()
#14 /sites/tex-upgrade/current/generated/code/Magento/TwoFactorAuth/Controller/Adminhtml/Tfa/Requestconfig/Interceptor.php(23): Magento\TwoFactorAuth\Controller\Adminhtml\Tfa\Requestconfig\Interceptor->___callPlugins('execute', Array, Array)
#15 /sites/tex-upgrade/current/vendor/magento/framework/App/Action/Action.php(111): Magento\TwoFactorAuth\Controller\Adminhtml\Tfa\Requestconfig\Interceptor->execute()
#16 /sites/tex-upgrade/current/vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#17 /sites/tex-upgrade/current/vendor/magento/module-two-factor-auth/Controller/Adminhtml/AbstractAction.php(30): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#18 /sites/tex-upgrade/current/vendor/magento/framework/Interception/Interceptor.php(58): Magento\TwoFactorAuth\Controller\Adminhtml\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#19 /sites/tex-upgrade/current/vendor/magento/framework/Interception/Interceptor.php(138): Magento\TwoFactorAuth\Controller\Adminhtml\Tfa\Requestconfig\Interceptor->___callParent('dispatch', Array)
#20 /sites/tex-upgrade/current/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\TwoFactorAuth\Controller\Adminhtml\Tfa\Requestconfig\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#21 /sites/tex-upgrade/current/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\TwoFactorAuth\Controller\Adminhtml\Tfa\Requestconfig\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#22 /sites/tex-upgrade/current/vendor/magento/framework/Interception/Interceptor.php(153): Magento\TwoFactorAuth\Controller\Adminhtml\Tfa\Requestconfig\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#23 /sites/tex-upgrade/current/generated/code/Magento/TwoFactorAuth/Controller/Adminhtml/Tfa/Requestconfig/Interceptor.php(32): Magento\TwoFactorAuth\Controller\Adminhtml\Tfa\Requestconfig\Interceptor->___callPlugins('dispatch', Array, Array)
#24 /sites/tex-upgrade/current/vendor/magento/framework/App/FrontController.php(186): Magento\TwoFactorAuth\Controller\Adminhtml\Tfa\Requestconfig\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#25 /sites/tex-upgrade/current/vendor/magento/framework/App/FrontController.php(118): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Magento\TwoFactorAuth\Controller\Adminhtml\Tfa\Requestconfig\Interceptor))
#26 /sites/tex-upgrade/current/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#27 /sites/tex-upgrade/current/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#28 /sites/tex-upgrade/current/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#29 /sites/tex-upgrade/current/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#30 /sites/tex-upgrade/current/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#31 /sites/tex-upgrade/current/vendor/magento/framework/App/Bootstrap.php(263): Magento\Framework\App\Http->launch()
#32 /sites/tex-upgrade/current/pub/index.php(38): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#33 {main} [] []
```

**Comment by flowmailer-richard** [comment]
Fixed in commit 56b5b06ae19b5599d494e44eca0d0585696ead27, will be released soon
